//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DivssPortal.DivssServiceRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DivssServiceSoap", Namespace="http://tempuri.org/")]
    public partial class DivssService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InsertInvoiceDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetItemDetailsByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllItemListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GelAllInvMastDetailsByInvNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GelAllInvDetail_DetailsByInvNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLatestValuesForDashboardOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertCustomerDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllCustomersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllCustomersByIdLikeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllCustomersByNameLikeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomersDetailsByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GeluserInfoLogingOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertuserInfoSignupOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DivssService() {
            this.Url = global::DivssPortal.Properties.Settings.Default.DivssPortal_DivssServiceRef_DivssService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InsertInvoiceDetailsCompletedEventHandler InsertInvoiceDetailsCompleted;
        
        /// <remarks/>
        public event GetItemDetailsByIDCompletedEventHandler GetItemDetailsByIDCompleted;
        
        /// <remarks/>
        public event GetAllItemListCompletedEventHandler GetAllItemListCompleted;
        
        /// <remarks/>
        public event GelAllInvMastDetailsByInvNoCompletedEventHandler GelAllInvMastDetailsByInvNoCompleted;
        
        /// <remarks/>
        public event GelAllInvDetail_DetailsByInvNoCompletedEventHandler GelAllInvDetail_DetailsByInvNoCompleted;
        
        /// <remarks/>
        public event GetLatestValuesForDashboardCompletedEventHandler GetLatestValuesForDashboardCompleted;
        
        /// <remarks/>
        public event InsertCustomerDetailsCompletedEventHandler InsertCustomerDetailsCompleted;
        
        /// <remarks/>
        public event GetAllCustomersCompletedEventHandler GetAllCustomersCompleted;
        
        /// <remarks/>
        public event GetAllCustomersByIdLikeCompletedEventHandler GetAllCustomersByIdLikeCompleted;
        
        /// <remarks/>
        public event GetAllCustomersByNameLikeCompletedEventHandler GetAllCustomersByNameLikeCompleted;
        
        /// <remarks/>
        public event GetCustomersDetailsByIdCompletedEventHandler GetCustomersDetailsByIdCompleted;
        
        /// <remarks/>
        public event GeluserInfoLogingCompletedEventHandler GeluserInfoLogingCompleted;
        
        /// <remarks/>
        public event InsertuserInfoSignupCompletedEventHandler InsertuserInfoSignupCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertInvoiceDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertInvoiceDetails(INV_MAST InvMast, INV_DETAILS[] InvDetails) {
            object[] results = this.Invoke("InsertInvoiceDetails", new object[] {
                        InvMast,
                        InvDetails});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertInvoiceDetailsAsync(INV_MAST InvMast, INV_DETAILS[] InvDetails) {
            this.InsertInvoiceDetailsAsync(InvMast, InvDetails, null);
        }
        
        /// <remarks/>
        public void InsertInvoiceDetailsAsync(INV_MAST InvMast, INV_DETAILS[] InvDetails, object userState) {
            if ((this.InsertInvoiceDetailsOperationCompleted == null)) {
                this.InsertInvoiceDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertInvoiceDetailsOperationCompleted);
            }
            this.InvokeAsync("InsertInvoiceDetails", new object[] {
                        InvMast,
                        InvDetails}, this.InsertInvoiceDetailsOperationCompleted, userState);
        }
        
        private void OnInsertInvoiceDetailsOperationCompleted(object arg) {
            if ((this.InsertInvoiceDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertInvoiceDetailsCompleted(this, new InsertInvoiceDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetItemDetailsByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ITEM_MAST GetItemDetailsByID(string ItemCode) {
            object[] results = this.Invoke("GetItemDetailsByID", new object[] {
                        ItemCode});
            return ((ITEM_MAST)(results[0]));
        }
        
        /// <remarks/>
        public void GetItemDetailsByIDAsync(string ItemCode) {
            this.GetItemDetailsByIDAsync(ItemCode, null);
        }
        
        /// <remarks/>
        public void GetItemDetailsByIDAsync(string ItemCode, object userState) {
            if ((this.GetItemDetailsByIDOperationCompleted == null)) {
                this.GetItemDetailsByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetItemDetailsByIDOperationCompleted);
            }
            this.InvokeAsync("GetItemDetailsByID", new object[] {
                        ItemCode}, this.GetItemDetailsByIDOperationCompleted, userState);
        }
        
        private void OnGetItemDetailsByIDOperationCompleted(object arg) {
            if ((this.GetItemDetailsByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetItemDetailsByIDCompleted(this, new GetItemDetailsByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllItemList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ITEM_MAST[] GetAllItemList() {
            object[] results = this.Invoke("GetAllItemList", new object[0]);
            return ((ITEM_MAST[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllItemListAsync() {
            this.GetAllItemListAsync(null);
        }
        
        /// <remarks/>
        public void GetAllItemListAsync(object userState) {
            if ((this.GetAllItemListOperationCompleted == null)) {
                this.GetAllItemListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllItemListOperationCompleted);
            }
            this.InvokeAsync("GetAllItemList", new object[0], this.GetAllItemListOperationCompleted, userState);
        }
        
        private void OnGetAllItemListOperationCompleted(object arg) {
            if ((this.GetAllItemListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllItemListCompleted(this, new GetAllItemListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GelAllInvMastDetailsByInvNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public INV_MAST GelAllInvMastDetailsByInvNo(string InvNo, string CompId) {
            object[] results = this.Invoke("GelAllInvMastDetailsByInvNo", new object[] {
                        InvNo,
                        CompId});
            return ((INV_MAST)(results[0]));
        }
        
        /// <remarks/>
        public void GelAllInvMastDetailsByInvNoAsync(string InvNo, string CompId) {
            this.GelAllInvMastDetailsByInvNoAsync(InvNo, CompId, null);
        }
        
        /// <remarks/>
        public void GelAllInvMastDetailsByInvNoAsync(string InvNo, string CompId, object userState) {
            if ((this.GelAllInvMastDetailsByInvNoOperationCompleted == null)) {
                this.GelAllInvMastDetailsByInvNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGelAllInvMastDetailsByInvNoOperationCompleted);
            }
            this.InvokeAsync("GelAllInvMastDetailsByInvNo", new object[] {
                        InvNo,
                        CompId}, this.GelAllInvMastDetailsByInvNoOperationCompleted, userState);
        }
        
        private void OnGelAllInvMastDetailsByInvNoOperationCompleted(object arg) {
            if ((this.GelAllInvMastDetailsByInvNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GelAllInvMastDetailsByInvNoCompleted(this, new GelAllInvMastDetailsByInvNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GelAllInvDetail_DetailsByInvNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public INV_DETAILS[] GelAllInvDetail_DetailsByInvNo(string InvNo, string CompId) {
            object[] results = this.Invoke("GelAllInvDetail_DetailsByInvNo", new object[] {
                        InvNo,
                        CompId});
            return ((INV_DETAILS[])(results[0]));
        }
        
        /// <remarks/>
        public void GelAllInvDetail_DetailsByInvNoAsync(string InvNo, string CompId) {
            this.GelAllInvDetail_DetailsByInvNoAsync(InvNo, CompId, null);
        }
        
        /// <remarks/>
        public void GelAllInvDetail_DetailsByInvNoAsync(string InvNo, string CompId, object userState) {
            if ((this.GelAllInvDetail_DetailsByInvNoOperationCompleted == null)) {
                this.GelAllInvDetail_DetailsByInvNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGelAllInvDetail_DetailsByInvNoOperationCompleted);
            }
            this.InvokeAsync("GelAllInvDetail_DetailsByInvNo", new object[] {
                        InvNo,
                        CompId}, this.GelAllInvDetail_DetailsByInvNoOperationCompleted, userState);
        }
        
        private void OnGelAllInvDetail_DetailsByInvNoOperationCompleted(object arg) {
            if ((this.GelAllInvDetail_DetailsByInvNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GelAllInvDetail_DetailsByInvNoCompleted(this, new GelAllInvDetail_DetailsByInvNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLatestValuesForDashboard", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public INV_MAST GetLatestValuesForDashboard(string CompId) {
            object[] results = this.Invoke("GetLatestValuesForDashboard", new object[] {
                        CompId});
            return ((INV_MAST)(results[0]));
        }
        
        /// <remarks/>
        public void GetLatestValuesForDashboardAsync(string CompId) {
            this.GetLatestValuesForDashboardAsync(CompId, null);
        }
        
        /// <remarks/>
        public void GetLatestValuesForDashboardAsync(string CompId, object userState) {
            if ((this.GetLatestValuesForDashboardOperationCompleted == null)) {
                this.GetLatestValuesForDashboardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLatestValuesForDashboardOperationCompleted);
            }
            this.InvokeAsync("GetLatestValuesForDashboard", new object[] {
                        CompId}, this.GetLatestValuesForDashboardOperationCompleted, userState);
        }
        
        private void OnGetLatestValuesForDashboardOperationCompleted(object arg) {
            if ((this.GetLatestValuesForDashboardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLatestValuesForDashboardCompleted(this, new GetLatestValuesForDashboardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertCustomerDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertCustomerDetails(string CustName, string VehicleModel, string CustPhone, string CustEmail, string CustAddress) {
            object[] results = this.Invoke("InsertCustomerDetails", new object[] {
                        CustName,
                        VehicleModel,
                        CustPhone,
                        CustEmail,
                        CustAddress});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertCustomerDetailsAsync(string CustName, string VehicleModel, string CustPhone, string CustEmail, string CustAddress) {
            this.InsertCustomerDetailsAsync(CustName, VehicleModel, CustPhone, CustEmail, CustAddress, null);
        }
        
        /// <remarks/>
        public void InsertCustomerDetailsAsync(string CustName, string VehicleModel, string CustPhone, string CustEmail, string CustAddress, object userState) {
            if ((this.InsertCustomerDetailsOperationCompleted == null)) {
                this.InsertCustomerDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertCustomerDetailsOperationCompleted);
            }
            this.InvokeAsync("InsertCustomerDetails", new object[] {
                        CustName,
                        VehicleModel,
                        CustPhone,
                        CustEmail,
                        CustAddress}, this.InsertCustomerDetailsOperationCompleted, userState);
        }
        
        private void OnInsertCustomerDetailsOperationCompleted(object arg) {
            if ((this.InsertCustomerDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertCustomerDetailsCompleted(this, new InsertCustomerDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllCustomers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CUSTOMER_MAST[] GetAllCustomers() {
            object[] results = this.Invoke("GetAllCustomers", new object[0]);
            return ((CUSTOMER_MAST[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllCustomersAsync() {
            this.GetAllCustomersAsync(null);
        }
        
        /// <remarks/>
        public void GetAllCustomersAsync(object userState) {
            if ((this.GetAllCustomersOperationCompleted == null)) {
                this.GetAllCustomersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllCustomersOperationCompleted);
            }
            this.InvokeAsync("GetAllCustomers", new object[0], this.GetAllCustomersOperationCompleted, userState);
        }
        
        private void OnGetAllCustomersOperationCompleted(object arg) {
            if ((this.GetAllCustomersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCustomersCompleted(this, new GetAllCustomersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllCustomersByIdLike", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CUSTOMER_MAST[] GetAllCustomersByIdLike(string CustId) {
            object[] results = this.Invoke("GetAllCustomersByIdLike", new object[] {
                        CustId});
            return ((CUSTOMER_MAST[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllCustomersByIdLikeAsync(string CustId) {
            this.GetAllCustomersByIdLikeAsync(CustId, null);
        }
        
        /// <remarks/>
        public void GetAllCustomersByIdLikeAsync(string CustId, object userState) {
            if ((this.GetAllCustomersByIdLikeOperationCompleted == null)) {
                this.GetAllCustomersByIdLikeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllCustomersByIdLikeOperationCompleted);
            }
            this.InvokeAsync("GetAllCustomersByIdLike", new object[] {
                        CustId}, this.GetAllCustomersByIdLikeOperationCompleted, userState);
        }
        
        private void OnGetAllCustomersByIdLikeOperationCompleted(object arg) {
            if ((this.GetAllCustomersByIdLikeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCustomersByIdLikeCompleted(this, new GetAllCustomersByIdLikeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllCustomersByNameLike", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CUSTOMER_MAST[] GetAllCustomersByNameLike(string CustName) {
            object[] results = this.Invoke("GetAllCustomersByNameLike", new object[] {
                        CustName});
            return ((CUSTOMER_MAST[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllCustomersByNameLikeAsync(string CustName) {
            this.GetAllCustomersByNameLikeAsync(CustName, null);
        }
        
        /// <remarks/>
        public void GetAllCustomersByNameLikeAsync(string CustName, object userState) {
            if ((this.GetAllCustomersByNameLikeOperationCompleted == null)) {
                this.GetAllCustomersByNameLikeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllCustomersByNameLikeOperationCompleted);
            }
            this.InvokeAsync("GetAllCustomersByNameLike", new object[] {
                        CustName}, this.GetAllCustomersByNameLikeOperationCompleted, userState);
        }
        
        private void OnGetAllCustomersByNameLikeOperationCompleted(object arg) {
            if ((this.GetAllCustomersByNameLikeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCustomersByNameLikeCompleted(this, new GetAllCustomersByNameLikeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCustomersDetailsById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CUSTOMER_MAST GetCustomersDetailsById(string CustID) {
            object[] results = this.Invoke("GetCustomersDetailsById", new object[] {
                        CustID});
            return ((CUSTOMER_MAST)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomersDetailsByIdAsync(string CustID) {
            this.GetCustomersDetailsByIdAsync(CustID, null);
        }
        
        /// <remarks/>
        public void GetCustomersDetailsByIdAsync(string CustID, object userState) {
            if ((this.GetCustomersDetailsByIdOperationCompleted == null)) {
                this.GetCustomersDetailsByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomersDetailsByIdOperationCompleted);
            }
            this.InvokeAsync("GetCustomersDetailsById", new object[] {
                        CustID}, this.GetCustomersDetailsByIdOperationCompleted, userState);
        }
        
        private void OnGetCustomersDetailsByIdOperationCompleted(object arg) {
            if ((this.GetCustomersDetailsByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomersDetailsByIdCompleted(this, new GetCustomersDetailsByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GeluserInfoLoging", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public USER_INFO GeluserInfoLoging(string UserName, string Password) {
            object[] results = this.Invoke("GeluserInfoLoging", new object[] {
                        UserName,
                        Password});
            return ((USER_INFO)(results[0]));
        }
        
        /// <remarks/>
        public void GeluserInfoLogingAsync(string UserName, string Password) {
            this.GeluserInfoLogingAsync(UserName, Password, null);
        }
        
        /// <remarks/>
        public void GeluserInfoLogingAsync(string UserName, string Password, object userState) {
            if ((this.GeluserInfoLogingOperationCompleted == null)) {
                this.GeluserInfoLogingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGeluserInfoLogingOperationCompleted);
            }
            this.InvokeAsync("GeluserInfoLoging", new object[] {
                        UserName,
                        Password}, this.GeluserInfoLogingOperationCompleted, userState);
        }
        
        private void OnGeluserInfoLogingOperationCompleted(object arg) {
            if ((this.GeluserInfoLogingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GeluserInfoLogingCompleted(this, new GeluserInfoLogingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertuserInfoSignup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertuserInfoSignup(string UserName, string Password, string Email) {
            object[] results = this.Invoke("InsertuserInfoSignup", new object[] {
                        UserName,
                        Password,
                        Email});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertuserInfoSignupAsync(string UserName, string Password, string Email) {
            this.InsertuserInfoSignupAsync(UserName, Password, Email, null);
        }
        
        /// <remarks/>
        public void InsertuserInfoSignupAsync(string UserName, string Password, string Email, object userState) {
            if ((this.InsertuserInfoSignupOperationCompleted == null)) {
                this.InsertuserInfoSignupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertuserInfoSignupOperationCompleted);
            }
            this.InvokeAsync("InsertuserInfoSignup", new object[] {
                        UserName,
                        Password,
                        Email}, this.InsertuserInfoSignupOperationCompleted, userState);
        }
        
        private void OnInsertuserInfoSignupOperationCompleted(object arg) {
            if ((this.InsertuserInfoSignupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertuserInfoSignupCompleted(this, new InsertuserInfoSignupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class INV_MAST {
        
        private string iNV_NOField;
        
        private System.Nullable<System.DateTime> iNV_DATEField;
        
        private System.Nullable<System.DateTime> iNV_TIMEField;
        
        private string cOMPANY_CODEField;
        
        private string uSER_CODEField;
        
        private string cUSTOMER_CODEField;
        
        private string iNV_TYPEField;
        
        private string mAINTAINANCE_TYPEField;
        
        private System.Nullable<decimal> tOTALField;
        
        private int aUTO_IDField;
        
        /// <remarks/>
        public string INV_NO {
            get {
                return this.iNV_NOField;
            }
            set {
                this.iNV_NOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> INV_DATE {
            get {
                return this.iNV_DATEField;
            }
            set {
                this.iNV_DATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> INV_TIME {
            get {
                return this.iNV_TIMEField;
            }
            set {
                this.iNV_TIMEField = value;
            }
        }
        
        /// <remarks/>
        public string COMPANY_CODE {
            get {
                return this.cOMPANY_CODEField;
            }
            set {
                this.cOMPANY_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string USER_CODE {
            get {
                return this.uSER_CODEField;
            }
            set {
                this.uSER_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string CUSTOMER_CODE {
            get {
                return this.cUSTOMER_CODEField;
            }
            set {
                this.cUSTOMER_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string INV_TYPE {
            get {
                return this.iNV_TYPEField;
            }
            set {
                this.iNV_TYPEField = value;
            }
        }
        
        /// <remarks/>
        public string MAINTAINANCE_TYPE {
            get {
                return this.mAINTAINANCE_TYPEField;
            }
            set {
                this.mAINTAINANCE_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> TOTAL {
            get {
                return this.tOTALField;
            }
            set {
                this.tOTALField = value;
            }
        }
        
        /// <remarks/>
        public int AUTO_ID {
            get {
                return this.aUTO_IDField;
            }
            set {
                this.aUTO_IDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class USER_INFO {
        
        private string uSER_CODEField;
        
        private string uSER_NAMEField;
        
        private string eMPLOYEE_IDField;
        
        private int aUTO_IDField;
        
        private string pASSWORDField;
        
        /// <remarks/>
        public string USER_CODE {
            get {
                return this.uSER_CODEField;
            }
            set {
                this.uSER_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string USER_NAME {
            get {
                return this.uSER_NAMEField;
            }
            set {
                this.uSER_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string EMPLOYEE_ID {
            get {
                return this.eMPLOYEE_IDField;
            }
            set {
                this.eMPLOYEE_IDField = value;
            }
        }
        
        /// <remarks/>
        public int AUTO_ID {
            get {
                return this.aUTO_IDField;
            }
            set {
                this.aUTO_IDField = value;
            }
        }
        
        /// <remarks/>
        public string PASSWORD {
            get {
                return this.pASSWORDField;
            }
            set {
                this.pASSWORDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CUSTOMER_MAST {
        
        private string cUST_IDField;
        
        private string cUST_NAMEField;
        
        private string vEHICLE_IDField;
        
        private string pHONEField;
        
        private string eMAILField;
        
        private string aDDRESSField;
        
        private System.Nullable<System.DateTime> vISITED_TIMEField;
        
        private int aUTO_IDField;
        
        /// <remarks/>
        public string CUST_ID {
            get {
                return this.cUST_IDField;
            }
            set {
                this.cUST_IDField = value;
            }
        }
        
        /// <remarks/>
        public string CUST_NAME {
            get {
                return this.cUST_NAMEField;
            }
            set {
                this.cUST_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string VEHICLE_ID {
            get {
                return this.vEHICLE_IDField;
            }
            set {
                this.vEHICLE_IDField = value;
            }
        }
        
        /// <remarks/>
        public string PHONE {
            get {
                return this.pHONEField;
            }
            set {
                this.pHONEField = value;
            }
        }
        
        /// <remarks/>
        public string EMAIL {
            get {
                return this.eMAILField;
            }
            set {
                this.eMAILField = value;
            }
        }
        
        /// <remarks/>
        public string ADDRESS {
            get {
                return this.aDDRESSField;
            }
            set {
                this.aDDRESSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> VISITED_TIME {
            get {
                return this.vISITED_TIMEField;
            }
            set {
                this.vISITED_TIMEField = value;
            }
        }
        
        /// <remarks/>
        public int AUTO_ID {
            get {
                return this.aUTO_IDField;
            }
            set {
                this.aUTO_IDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ITEM_MAST {
        
        private string iTEM_CODEField;
        
        private string cOMPANY_CODEField;
        
        private string iTEM_DESCField;
        
        private string uNITField;
        
        private string mANUFACTURERField;
        
        private string cOUNTRYField;
        
        private System.Nullable<decimal> sTOCKField;
        
        private System.Nullable<decimal> pRIZEField;
        
        private int aUTO_IDField;
        
        /// <remarks/>
        public string ITEM_CODE {
            get {
                return this.iTEM_CODEField;
            }
            set {
                this.iTEM_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string COMPANY_CODE {
            get {
                return this.cOMPANY_CODEField;
            }
            set {
                this.cOMPANY_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string ITEM_DESC {
            get {
                return this.iTEM_DESCField;
            }
            set {
                this.iTEM_DESCField = value;
            }
        }
        
        /// <remarks/>
        public string UNIT {
            get {
                return this.uNITField;
            }
            set {
                this.uNITField = value;
            }
        }
        
        /// <remarks/>
        public string MANUFACTURER {
            get {
                return this.mANUFACTURERField;
            }
            set {
                this.mANUFACTURERField = value;
            }
        }
        
        /// <remarks/>
        public string COUNTRY {
            get {
                return this.cOUNTRYField;
            }
            set {
                this.cOUNTRYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> STOCK {
            get {
                return this.sTOCKField;
            }
            set {
                this.sTOCKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PRIZE {
            get {
                return this.pRIZEField;
            }
            set {
                this.pRIZEField = value;
            }
        }
        
        /// <remarks/>
        public int AUTO_ID {
            get {
                return this.aUTO_IDField;
            }
            set {
                this.aUTO_IDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class INV_DETAILS {
        
        private string iNV_NOField;
        
        private string iTEMS_FOR_MAINTAINANCEField;
        
        private System.Nullable<decimal> qTYField;
        
        private System.Nullable<decimal> pRICEField;
        
        private string sUB_TOTField;
        
        private string sERVICE_TYPEField;
        
        private System.Nullable<decimal> sERVICE_PRICEField;
        
        private string sUB_SERVICE_TOTField;
        
        private string cOMPANY_CODEField;
        
        private string iTEM_DESCField;
        
        private int aUTO_IDField;
        
        /// <remarks/>
        public string INV_NO {
            get {
                return this.iNV_NOField;
            }
            set {
                this.iNV_NOField = value;
            }
        }
        
        /// <remarks/>
        public string ITEMS_FOR_MAINTAINANCE {
            get {
                return this.iTEMS_FOR_MAINTAINANCEField;
            }
            set {
                this.iTEMS_FOR_MAINTAINANCEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> QTY {
            get {
                return this.qTYField;
            }
            set {
                this.qTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PRICE {
            get {
                return this.pRICEField;
            }
            set {
                this.pRICEField = value;
            }
        }
        
        /// <remarks/>
        public string SUB_TOT {
            get {
                return this.sUB_TOTField;
            }
            set {
                this.sUB_TOTField = value;
            }
        }
        
        /// <remarks/>
        public string SERVICE_TYPE {
            get {
                return this.sERVICE_TYPEField;
            }
            set {
                this.sERVICE_TYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> SERVICE_PRICE {
            get {
                return this.sERVICE_PRICEField;
            }
            set {
                this.sERVICE_PRICEField = value;
            }
        }
        
        /// <remarks/>
        public string SUB_SERVICE_TOT {
            get {
                return this.sUB_SERVICE_TOTField;
            }
            set {
                this.sUB_SERVICE_TOTField = value;
            }
        }
        
        /// <remarks/>
        public string COMPANY_CODE {
            get {
                return this.cOMPANY_CODEField;
            }
            set {
                this.cOMPANY_CODEField = value;
            }
        }
        
        /// <remarks/>
        public string ITEM_DESC {
            get {
                return this.iTEM_DESCField;
            }
            set {
                this.iTEM_DESCField = value;
            }
        }
        
        /// <remarks/>
        public int AUTO_ID {
            get {
                return this.aUTO_IDField;
            }
            set {
                this.aUTO_IDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void InsertInvoiceDetailsCompletedEventHandler(object sender, InsertInvoiceDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertInvoiceDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertInvoiceDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetItemDetailsByIDCompletedEventHandler(object sender, GetItemDetailsByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetItemDetailsByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetItemDetailsByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ITEM_MAST Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ITEM_MAST)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetAllItemListCompletedEventHandler(object sender, GetAllItemListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllItemListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllItemListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ITEM_MAST[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ITEM_MAST[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GelAllInvMastDetailsByInvNoCompletedEventHandler(object sender, GelAllInvMastDetailsByInvNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GelAllInvMastDetailsByInvNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GelAllInvMastDetailsByInvNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public INV_MAST Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((INV_MAST)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GelAllInvDetail_DetailsByInvNoCompletedEventHandler(object sender, GelAllInvDetail_DetailsByInvNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GelAllInvDetail_DetailsByInvNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GelAllInvDetail_DetailsByInvNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public INV_DETAILS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((INV_DETAILS[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetLatestValuesForDashboardCompletedEventHandler(object sender, GetLatestValuesForDashboardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLatestValuesForDashboardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLatestValuesForDashboardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public INV_MAST Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((INV_MAST)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void InsertCustomerDetailsCompletedEventHandler(object sender, InsertCustomerDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertCustomerDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertCustomerDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetAllCustomersCompletedEventHandler(object sender, GetAllCustomersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCustomersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCustomersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CUSTOMER_MAST[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CUSTOMER_MAST[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetAllCustomersByIdLikeCompletedEventHandler(object sender, GetAllCustomersByIdLikeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCustomersByIdLikeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCustomersByIdLikeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CUSTOMER_MAST[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CUSTOMER_MAST[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetAllCustomersByNameLikeCompletedEventHandler(object sender, GetAllCustomersByNameLikeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCustomersByNameLikeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCustomersByNameLikeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CUSTOMER_MAST[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CUSTOMER_MAST[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetCustomersDetailsByIdCompletedEventHandler(object sender, GetCustomersDetailsByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomersDetailsByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomersDetailsByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CUSTOMER_MAST Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CUSTOMER_MAST)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GeluserInfoLogingCompletedEventHandler(object sender, GeluserInfoLogingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GeluserInfoLogingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GeluserInfoLogingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public USER_INFO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((USER_INFO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void InsertuserInfoSignupCompletedEventHandler(object sender, InsertuserInfoSignupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertuserInfoSignupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertuserInfoSignupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591